export const CREATE_COURSE = "CREATE_COURSE";
export const UPDATE_MODULE = "UPDATE_MODULE";
export const ACTIVE_LESSON = "ACTIVE_LESSON";

export const CREATE_COURSE_ERROR = "CREATE_COURSE_ERROR";
export const GET_ALL_COURSE = "GET_ALL_COURSE";
